### PR TITLE
SkyUX referenced via CDN instead of Bower components.

### PR DESCRIPTION
**Pull request by Blackbaud-SteveBrush**

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
@Blackbaud-SteveBrush  Does this affect the `grunt build` step in anyway?

**Comment by Blackbaud-SteveBrush** [comment]
I made some changes to the Gruntfile.js to remove the local versions of the SkyUX files. Didn't affect other build tasks, however.

**Comment by Blackbaud-BobbyEarl** [comment]
Looks good @Blackbaud-SteveBrush

**Comment by Blackbaud-SteveBrush** [comment]
Awesome thanks, @Blackbaud-BobbyEarl. I don't have write access to this repo, so one of y'all will have to merge.

**Comment by Blackbaud-SteveBrush** [comment]
Added results of the build.

**Comment by Blackbaud-SteveBrush** [comment]
Please check index.html. I added the Barkbaud inline module at the bottom of the page, instead of having Barkbaud's gruntfile itself do that.

**Comment by Blackbaud-BobbyEarl** [comment]
The reason the config module was added in barkbaud, is it allows local development of barkbaud-ui to point to deployment API URL  Barkbaud then adds `/` as the API URL during the build step so that it will work regardless of the URL where it's deployed.

Moving this means you would also need barkbaud running locally when developing barkbaud-ui.

I don't disagree that there's a better pattern there, just know that adding that snippet will have that effect.

**Comment by Blackbaud-SteveBrush** [comment]
Removed inline app, @Blackbaud-BobbyEarl. Thanks again for taking a look at this!

**Comment by Blackbaud-BobbyEarl** [comment]
Looks good @Blackbaud-SteveBrush

**Pull request merged**
