### PR TITLE
Uib upgrade

### PR DESCRIPTION
**Pull request by Blackbaud-PatrickOFriel**
Updating to a more recent version of SkyUX and using `$uibModalInstance` instead of `$modalInstance`. Later, I'd like to add some more updates: like using a selectField control instead of a ui-select control (which is deprecated in SkyUX 1.6.0), using the SkyUX page summary directive, and the SkyUX repeater directive.

### CODE REVIEW

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-SteveBrush @Blackbaud-PaulCrowder @Blackbaud-BobbyEarl anyone want to look at this?

**Comment by Blackbaud-BobbyEarl** [comment]
Approved

**Comment by Blackbaud-SteveBrush** [comment]
Has this been tested with the barkbaud heroku app? If not, I can do that July 6 morning.

**Comment by Blackbaud-PatrickOFriel** [comment]
Do you mean just spinning it up and locally and hitting the heroku backend? Because yes, but I wouldn't mind another set of eyes looking at it

**Comment by Blackbaud-SteveBrush** [comment]
Yep; I'll do a quick run through today.

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-PatrickOFriel: Tested on local version of barkbaud server and all is well. Approved.

**Comment by Blackbaud-PatrickOFriel** [comment]
Could you go ahead and merge it? I don't have write access here

**Pull request merged**
